### ISSUE TITLE
Convert to AsciiDoc and translate last available version of Admin Manual

### ISSUE THREAD

**Issue by gmarpons** [decidim/documentation#13]
We have a newer version of the Administration Manual (at least v0.17). Unfortunately I'm not sure we have this version in English. It needs to be converted from Google Docs to AsciiDoc.

**Comment by andreslucena** [comment]
Right now is mandatory to have it translated to English, as currently is the only supported language that we have on documentation. I've changed the title to reflect that.

This is the document in .docx (GitHub doesn't allow uploading .odt :angry:):

[AdministracióDecidim CAST_Decidim v.0.17.docx](https://github.com/decidim/documentation/files/5029406/AdministracioDecidim.CAST_Decidim.v.0.17.docx)

I've made a quick test with deepl.com and it's actually pretty good: 

<details>
  <summary>Translation test from deepl.com</summary>
  
Complete the following fields (remember that if the platform is in two or more languages, the information must be completed in the different languages):
    - Title: name of the participatory process.
    - Subtitle: subtitle of the participatory process.
    - Short URL text: word that identifies the web page where the general information about the process will be found. For example, "name of the process", https://decidim.nomdelmunicipi.com/processes/nombredelproceso.
    - Hashtag: social network label, the same one that will be used in networking campaigns, Twitter, Facebook, Instagram, etc. (one word only)
    - Start date: select the start date of the participatory process
    - End date: selects the end date of the participatory process.
    - Highlighted: check this box if you want to highlight the process on the platform's homepage.
    - Short description: brief explanation of the participatory process in maximum 600 characters.
    - Description: description of the participatory process. From 1600 characters onwards a "Read more" will be displayed.
    - Cover image: image associated to the participatory process that appears in the general page of processes (Figure 26) and in the main page of the Decidim platform, if the highlight option has been marked (Figure 27) (minimum dimensions: 1,015 px width × 667 px height).
    - Banner image: image for all the pages of the process. It is published at the top of the pages, from left to right (Figure 28) (minimum dimensions: 1200 px width × 300 px height).
    - Promoting group: person(s) managing and responsible for the participatory process.
    - Organizational area: areas of the organization involved in the participatory process.
    - Scope metadata: internal information on the city scope to which the process is addressed. Field that will not be public.
    - Who participates: people for whom the participatory process is intended.
    - Qualified areas: must be marked if you wish to identify with an area of action (municipal, district 1, district 2...).
    - Scope: select the corresponding scope from the drop-down menu. Previously, the scopes must have been created1.
    - What is decided: explanation of the margin or limits of decision that the participants will have in this participative process.
    - How it is decided: methodology for making decisions in the participatory process.

Translated with www.DeepL.com/Translator (free version)
  
</details> 

I think we could have a first version using: 
1. Deepl.com
2. Reviewing that the vocabulary/glossary is the same as the one being used on Decidim 

Regarding the conversion to AsciiDoc, what do you recommend? [pandoc](https://asciidoctor.org/docs/migrating-from-msword/)?

Finally, this .docx is *only* of v0.17 (March 2019)... but the current published English version is of v0.10 (March 2018)  :skull: :skull: - so making the comparison is a huuuuge step to be at least on the past year. We'd still need to update it to the last version 0.22 (still on the release candidate, August 2020), but as I said, step by step :smile:

**Comment by gmarpons** [comment]
So, do we agree on translating Admin Manual v0.17 into English?

> Regarding the conversion to AsciiDoc, what do you recommend? pandoc?

Yes. I have some experience with it, I can try.

**Comment by gmarpons** [comment]
I still don't have a clear strategy to get the Admin Manual translated. I paste here [two AsciiDoc files (in a zip)](https://github.com/decidim/documentation/files/5071680/AdminManual_ES.zip), one for version 0.10 and the other for version 0.17. Both are in Spanish and could be useful to get a diff and see what sentences have changed since v0.10, and then try to update the English version accordingly.

The source file for the v0.10 is: [AdministracióDecidim.CAST_Decidim.v.0.10.docx](https://github.com/decidim/documentation/files/5071710/AdministracioDecidim.CAST_Decidim.v.0.10.docx)

I've got both files with the following command:

`pandoc --to=asciidoctor --wrap=none --atx-headers --extract-media=images --output=admin-manual_v0.XX_ES.adoc AdministracioDecidim.CAST_Decidim.v.0.XX.docx`

I'll be the next two weeks on vacation. I encourage anyone to move this forward in the meantime.

**Comment by andreslucena** [comment]
Closing this issue as we've finally do again much of the old manuals. Thanks for your help with the doc site @gmarpons!!

**Comment by gmarpons** [comment]
You're welcome @andreslucena! I would have liked to help more with this effort and I'm happy that you've finally found a way forward.
