### ISSUE TITLE
Proposal: Remove gendered references in the docs 

### ISSUE THREAD

**Issue by RCheesley** [decidim/documentation#145]
Hi folks!

I want to propose making a PR to remove the (many) gender references (he/she/his/hers/him/her etc) and instead replace them with more inclusive gender neutral terms.

This is considered best practice in many documentation and writing style guides, some examples:

Google: https://developers.google.com/style/inclusive-documentation
EU: https://publications.europa.eu/code/en/en-4100600en.htm 
UN: https://www.un.org/en/gender-inclusive-language/guidelines.shtml

I'm happy to work on a PR but it will be large touch a lot of parts of the docs, and therefore might cause some work for translators.

Figured it would make sense to ask if such a PR will be accepted before launching into it!

**Comment by alecslupu** [comment]
I would say "go for it", but @decidim/product decides.

**Comment by RCheesley** [comment]
OK, will wait for the big green tick mark before I get started! ✅ 🤞

**Comment by andreslucena** [comment]
@RCheesley yes, go ahead!! 

FYI I made this PR in the main repository too about this same issue: https://github.com/decidim/decidim/pull/8684

**Comment by RCheesley** [comment]
Ah great - I will work on this over the next couple of weeks as I have some time off work!
