### ISSUE TITLE
Mention persistent volumes for docker setups

### ISSUE THREAD

**Issue by arusa** [decidim/documentation#41]
I haven't found any info about persistent storage in the documentation. I had to learn the hard way, that decidim uploads files to "public/uploads/".

Please add information, that a persistent volume needs to be created for "public/uploads" to at least this page: https://docs.decidim.org/en/develop/docker/

Are there any more directories that need to be persistent? Is it possible to use s3 compatible storage for uploads?

**Comment by oliverbarnes** [comment]
Thanks for bringing this up, @arusa. Things are in a flux regarding docker support and documentation. Did you come across the upload volume requirement using the development flow described on that doc (using the `d/rails`, `d/rake` stubs) or on your production deployment? Knowing your use case will help us on how to best document this.

**Comment by arusa** [comment]
I have created a development environment using docker that is working fine, because it mounts all app data into the container.
My problem was after deploying to a pre-production (still working on it) dokku environment. Dokku is like Heroku and every time a run a deployment the container gets created completely new. It was my fault not to think about decidim probably needing a persistent volume, but after finding out, that uploaded files got missing after a new deploy I researched a little bit and could not find any documentation where decidim is putting files that need to be stored persistent.

With a little bit of debugging I found out, that the uploaded files get created in public/uploads and so I created a persistent docker volume for this.

**Comment by oliverbarnes** [comment]
Yeah, the persistent volume will be required in any docker deployment that needs to support file uploads, not just on Dokku or Heroku. And the file storage location is not specific to Decidim, but to Rails - you can find more about it on their [Active Storage guide](https://guides.rubyonrails.org/active_storage_overview.html). There you'll find how to configure S3, for example.

We're [figuring out what to document and where](https://github.com/decidim/docker/discussions/80), but it's clear to me we should at least have the above information available. 

Meanwhile, see if this [docker-compose.yml](https://github.com/AjuntamentDeSabadell/decidim-sabadell/blob/master/docker-compose.yml) from the Decidim instance for the city of Sabadell helps? It has volumes setup for uploads and for logs, as well as ssl certs, and several other useful deployment configs.

**Comment by arusa** [comment]
Thanks! The information that ActiveStorage is being used helps a lot. That's perfect!

**Comment by oliverbarnes** [comment]
@arusa if you get a chance, would you please have a peek at https://github.com/decidim/decidim/pull/7311? It updates the PRs with what we discussed here.

**Comment by arusa** [comment]
@oliverbarnes looks good for me. Thanks :-)

**Comment by mrcasals** [comment]
Closing this, then! Please, leave a comment if you think this is not solved!
