### ISSUE TITLE
Automatically building the site

### ISSUE THREAD

**Issue by mrcasals** [decidim/documentation#43]
This site pulls info from https://github.com/decidim/decidim, but when that site's docs are updated, this repo doesn't get notified, so it can't rebuild the whole site. It seems that the site is deployed to Netlify and built directly there, and I don't think we have a way to trigger new builds except by pushing a new commit. This can be potentially problematic because docs might get updated at https://github.com/decidim/decidim but not deployed unless someone manually creates a commit in the `master` branch of this repo.

In order to fix this, I see three different options:

1. Manually creating empty commits to trigger rebuilds every time an update is made to the docs in `decidim/decidim. Can cause issues if someone forgets to commit.
2. Have a GitHub Actions triggering empty commits every day to force the rebuild. Can potentially cause a lot of empty, useless commits.
3. Move the build from Netlify from GitHub Actions, and rebuild the site every day. We could push changes only if they exist, for example, or push the new build every day regardless of the changes. Helps having a clean git history and is automatized, but requires some work to move the build from Netlify to here. Also requires to store things in Secrets, like the API key to push.

@andreslucena I'd go for the 3rd option, what do you think?

**Comment by oliverbarnes** [comment]
A milder version of 2) might be to have a github dispatch sent from decidim/decidim when docs are updated there, so an empty commit is created on decidim/docker? In which case it would only be as frequent as updates to docs there.

Here's a dispatch we have from decidim/decidim to decidim/docker: https://github.com/decidim/decidim/blob/develop/.github/workflows/on_release.yml

**Comment by mrcasals** [comment]
@oliverbarnes ah, this looks interesting, yes! I'm not sure if we can filter Actions by commits affecting a path, though, so we'd need to explore that...

**Comment by oliverbarnes** [comment]
you can :) with `on.push.paths`: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths

**Comment by mrcasals** [comment]
Ah, then we could catch the dispatch and create an empty commit using https://github.com/stefanzweifel/git-auto-commit-action (it seems to allow flags so we could use the `--allow-empty` one)

**Comment by oliverbarnes** [comment]
Cool, that's new to me - seems like it could work! And if the git history gets too noisy with empty commits down the line, we can always switch to 3), adapting the inter-repo dispatch to trigger it.

**Comment by mrcasals** [comment]
Yeah, we use it to automatize Review Apps creation in Codegram's Decidim staging application https://github.com/codegram/decidim-staging/

**Comment by mrcasals** [comment]
See #45 and 9999daeb32bdc8ea13281f187393ea1ef5d49b57 for a workflow that creates empty commits on demand. We can trigger this workflow from `decidim/decidim` and whatever other repo to trigger the build.

**Comment by andreslucena** [comment]
This was solved in #7360. Closing this issue. Thanks, @mrcasals @oliverbarnes 🚀 🚀
