### ISSUE TITLE
"Edit this page" - link broken

### ISSUE THREAD

**Issue by severinraez** [decidim/documentation#50]
E.g on https://docs.decidim.org/en/ the Link points to https://github.com/decidim/documentation/edit/HEAD/en/modules/ROOT/pages/index.adoc
For me this breaks, a working link is https://github.com/decidim/documentation/edit/master/en/modules/ROOT/pages/index.adoc - `master` instead of `HEAD`.

**Comment by andreslucena** [comment]
Thanks for the report @severinraez and sorry for the delay, I didn't have time to review this issue until now. It is working, depending on the page that you're it will send you to different repositories and branches.

**Comment by andreslucena** [comment]
For better tracking the fix in the future, fixed in several commits: f0234e0d2d3f304fed268052f67ce45857081991 eb3e69e85b7f77455af2e00183b0825e3fe512fb da13b4a595ebd81dc3cb874e99c5a87b12e05311
