### ISSUE TITLE
How to use the Decidim cookie consent and how to document the site cookies

### ISSUE THREAD

**Issue by ahukkanen** [decidim/documentation#94]
Right now we are implementing the cookie consent to Decidim at:
https://github.com/decidim/decidim/pull/9271

We should also add to documentation how to use the cookie consent system. At least the following issues would be important to mention:
1. What are the different cookie categories available in Decidim?
2. How to add scripts to the page which require cookie consent?
3. How to document the cookies for different categories for your own Decidim instance?

**Comment by andreslucena** [comment]
I was thinking to have it like a page in Configure - Customize, so: 

1. It'd be at docs/modules/customize/pages/cookies.adoc in decidim/decidim reposistory
2. As it's a new page, it needs to be added to https://github.com/decidim/documentation/blob/master/en/modules/ROOT/nav.adoc 

If you want to test it out locally, there's some docs about how to get it running on https://github.com/decidim/documentation/blob/master/README.md and https://github.com/decidim/decidim/blob/develop/docs/README.adoc

**Comment by ahukkanen** [comment]
The documentation page is already live at:
https://docs.decidim.org/en/customize/data_consent.html

The remaining navigation issues are being addressed by #109 and decidim/decidim#9828.
